apiVersion: v1alpha1
kind: ServiceTemplate
metadata:
  name: nginx
  platforms:
    - linux
spec:
  description: An HTTP and reverse proxy server
  icon: https://docker-application-template.s3.amazonaws.com/assets/nginx.png
  parameters:
  - defaultValue: "80"
    description: External port
    name: externalPort
    type: hostPort
  source:
    image: docker.io/__ORG__/nginx:__TAG__
  title: nginx
